### ISSUE TITLE
Question about CMS_22

### ISSUE THREAD

**Issue by mweng1024** [CMSgov/qpp-conversion-tool#912]
Hi,

We are trying to validate our QRDA III files for the 2019 reporting period using the QPP validation tool. https://github.com/CMSgov/qpp-conversion-tool
All of our files validate successfully with the exception of the files for CMS 22. Apparently the validator seems to think we have the wrong GUIDs. We have confirmed that file pass Cypress validation for the same reporting period.  The GUID we for CMS22 is 40280382-610b-e7a4-0161-9a3a392c37d5 which is matching the Cypress

Attached QRDA-III and error file

INFO - Transform invoked
INFO - Decoded template ID CLINICAL_DOCUMENT
INFO - Validating all nodes in the tree
ERROR - MEASURE_GUID_MISSING 40280382-610b-e7a4-0161-9a3a392c37d5
ERROR - There were errors during conversion. Writing out errors to CMS_22-error.json
gov.cms.qpp.conversion.model.error.TransformException: Validation errors exist
at gov.cms.qpp.conversion.Converter.transform(Converter.java:89)
at gov.cms.qpp.conversion.ConversionFileWriterWrapper.executeConverter(ConversionFileWriterWrapper.java:64)
at gov.cms.qpp.conversion.ConversionFileWriterWrapper.transform(ConversionFileWriterWrapper.java:54)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at gov.cms.qpp.conversion.CommandLineRunner.run(CommandLineRunner.java:83)
at gov.cms.qpp.conversion.CommandLineMain.main(CommandLineMain.java:45)

### Other details
I also found CMS 22, MeasureUuid were missing in following file

https://raw.githubusercontent.com/CMSgov/qpp-measures-data/master/measures/2019/measures-data.json

[CMS_22.zip](https://github.com/CMSgov/qpp-conversion-tool/files/3842899/CMS_22.zip)

**Comment by saquino0827** [comment]
Hi mewing1024,
CMS22v7 is currently incorrect right now. A fix has already been made and am awaiting approval before merge the fix into the conversion tool repo. I apologize for the wait.

**Comment by mweng1024** [comment]
Hi, does the fix merge into master yet? I am still seeing the same error when executed convert.sh

**Comment by saquino0827** [comment]
Hi Mweng,
The fix was in a separate repository that holds all the UUID data. I will be making a PR today to add in the changes and will be getting deployed to develop today or tomorrow. I will let you know once the the `develop` branch is updated as this should be sooner than the deployment if you are running locally.

**Comment by mweng1024** [comment]
Yes, I am running locally, please update me after  code merge to develop branch.

Thanks!

**Comment by saquino0827** [comment]
Hi Mweng,
Develop has been updated to use the correct CMS22v7 UUID's. Please run a new build and let me know If you have any more problems.

**Comment by saquino0827** [comment]
Closing due to inactivity. Feel free to open another issue if anything comes up.
